defmodule SpectreDirective.Planning.Guided do
  @moduledoc """
  Step-by-step initial planning.

  Guided planning spends more model calls to get a plan that is easier to steer:

  1. ask for a strategy,
  2. ask for one next step,
  3. insert the parsed step,
  4. ask for the next step or `Finish: reason`,
  5. stop on finish or `:planning_max_steps`.

  This is useful when the agent should reason incrementally instead of producing
  a whole plan in one draft.
  """

  alias SpectreDirective.CapabilitySnapshot
  alias SpectreDirective.Knowledge
  alias SpectreDirective.MissionBlueprint
  alias SpectreDirective.Plan
  alias SpectreDirective.Planning.DraftParser
  alias SpectreDirective.Planning.Request
  alias SpectreDirective.Planning.TextProvider
  alias SpectreDirective.Step

  @type trace :: {atom(), binary(), term()}
  @type result :: {:ok, Plan.t(), [trace()]} | {:error, term()}
  @type collection :: {:ok, [Step.t()], [binary()], term()} | {:error, term()}
  @type context :: %{
          required(:provider) => TextProvider.provider(),
          required(:blueprint) => MissionBlueprint.t(),
          required(:knowledge) => Knowledge.t(),
          required(:capabilities) => CapabilitySnapshot.t(),
          required(:strategy) => binary(),
          required(:opts) => keyword(),
          required(:max_steps) => pos_integer()
        }

  @default_max_steps 6

  @doc """
  Builds a plan one model turn at a time.
  """
  @spec build(
          TextProvider.provider(),
          MissionBlueprint.t(),
          Knowledge.t(),
          CapabilitySnapshot.t(),
          keyword()
        ) :: result()
  def build(provider, blueprint, knowledge, capabilities, opts) do
    with {:ok, strategy} <- ask_strategy(provider, blueprint, knowledge, capabilities, opts),
         context <- context(provider, blueprint, knowledge, capabilities, strategy, opts),
         {:ok, steps, step_drafts, finish_reason} <- collect_steps(context) do
      plan =
        steps
        |> Plan.new(source: :agent_generated, reason: "Generated by guided textual planning.")

      {:ok, plan, trace(plan, strategy, step_drafts, finish_reason)}
    end
  end

  @spec context(
          TextProvider.provider(),
          MissionBlueprint.t(),
          Knowledge.t(),
          CapabilitySnapshot.t(),
          binary(),
          keyword()
        ) :: context()
  defp context(provider, blueprint, knowledge, capabilities, strategy, opts) do
    %{
      provider: provider,
      blueprint: blueprint,
      knowledge: knowledge,
      capabilities: capabilities,
      strategy: strategy,
      opts: opts,
      max_steps: Keyword.get(opts, :planning_max_steps, @default_max_steps)
    }
  end

  @spec ask_strategy(
          TextProvider.provider(),
          MissionBlueprint.t(),
          Knowledge.t(),
          CapabilitySnapshot.t(),
          keyword()
        ) :: {:ok, binary()} | {:error, term()}
  defp ask_strategy(provider, blueprint, knowledge, capabilities, opts) do
    blueprint
    |> Request.guided_strategy(knowledge, capabilities, opts)
    |> call_text(provider, opts)
  end

  @spec collect_steps(context()) :: collection()
  defp collect_steps(context), do: do_collect_steps(context, [], [], 1)

  @spec do_collect_steps(context(), [Step.t()], [binary()], pos_integer()) :: collection()
  defp do_collect_steps(%{max_steps: max_steps}, [], _drafts, index) when index > max_steps do
    {:error, :guided_planner_returned_no_steps}
  end

  defp do_collect_steps(%{max_steps: max_steps}, steps, drafts, index) when index > max_steps do
    {:ok, steps, drafts, :max_steps_reached}
  end

  defp do_collect_steps(context, steps, drafts, index) do
    request =
      Request.guided_step(
        context.blueprint,
        context.knowledge,
        context.capabilities,
        context.strategy,
        steps,
        index,
        context.opts
      )

    with {:ok, draft} <- call_text(request, context.provider, context.opts) do
      handle_step_draft(
        DraftParser.parse_next_step(draft),
        context,
        steps,
        drafts ++ [draft],
        index
      )
    end
  end

  @spec handle_step_draft(
          {:ok, Step.t()} | {:finish, binary()} | {:error, term()},
          context(),
          [Step.t()],
          [binary()],
          pos_integer()
        ) :: collection()
  defp handle_step_draft({:finish, reason}, _context, [], _drafts, _index) do
    {:error, {:guided_planner_finished_without_steps, reason}}
  end

  defp handle_step_draft({:finish, reason}, _context, steps, drafts, _index) do
    {:ok, steps, drafts, reason}
  end

  defp handle_step_draft({:ok, %Step{kind: :finish} = step}, _context, steps, drafts, _index) do
    {:ok, steps ++ [step], drafts, "finish step generated"}
  end

  defp handle_step_draft({:ok, %Step{} = step}, context, steps, drafts, index) do
    do_collect_steps(context, steps ++ [step], drafts, index + 1)
  end

  defp handle_step_draft({:error, reason}, _context, [], _drafts, _index) do
    {:error, {:guided_step_parse_failed, reason}}
  end

  defp handle_step_draft({:error, reason}, _context, steps, drafts, _index) do
    {:ok, steps, drafts, {:stopped_after_parse_error, reason}}
  end

  @spec call_text(Request.t(), TextProvider.provider(), keyword()) ::
          {:ok, binary()} | {:error, term()}
  defp call_text(%Request{} = request, provider, opts) do
    case TextProvider.call(provider, request, opts) do
      {:ok, text} when is_binary(text) -> {:ok, text}
      text when is_binary(text) -> {:ok, text}
      {:error, reason} -> {:error, reason}
      other -> {:error, {:invalid_planning_text, other}}
    end
  end

  @spec trace(Plan.t(), binary(), [binary()], term()) :: [trace()]
  defp trace(%Plan{} = plan, strategy, drafts, finish_reason) do
    [
      {:planned, "Generated guided initial plan with #{length(plan.steps)} step(s).",
       %{
         mode: :guided,
         plan_id: plan.id,
         strategy: strategy,
         step_drafts: drafts,
         finish_reason: finish_reason,
         steps: Enum.map(plan.steps, & &1.title)
       }}
    ]
  end
end
