defmodule SpectreDirective.Planning.Session do
  @moduledoc """
  Runtime state for manual guided planning.
  """

  alias SpectreDirective.CapabilitySnapshot
  alias SpectreDirective.Knowledge
  alias SpectreDirective.MissionBlueprint
  alias SpectreDirective.Plan
  alias SpectreDirective.Planning.DraftParser
  alias SpectreDirective.Planning.Proposal
  alias SpectreDirective.Planning.Request
  alias SpectreDirective.Planning.TextProvider
  alias SpectreDirective.Step

  @proposal_types [:strategy, :step, :finish, :correction]

  @type t :: %__MODULE__{
          strategy: binary() | nil,
          steps: [Step.t()],
          pending: Proposal.t() | nil,
          turn: non_neg_integer(),
          feedback: [binary()],
          finish_reason: binary() | nil,
          fallback_plan: Plan.t()
        }

  defstruct [
    :strategy,
    :pending,
    :finish_reason,
    :fallback_plan,
    turn: 0,
    steps: [],
    feedback: []
  ]

  @doc """
  Creates an empty manual planning session.
  """
  @spec new(Plan.t()) :: t()
  def new(%Plan{} = fallback_plan), do: %__MODULE__{fallback_plan: fallback_plan}

  @doc """
  Returns data suitable for public inspection.
  """
  @spec public(t()) :: map()
  def public(%__MODULE__{} = session) do
    %{
      strategy: session.strategy,
      steps: session.steps,
      pending: session.pending,
      turn: session.turn,
      feedback: session.feedback,
      finish_reason: session.finish_reason
    }
  end

  @doc """
  Calls a text provider once and stores the resulting proposal as pending.
  """
  @spec propose(
          t(),
          TextProvider.provider(),
          MissionBlueprint.t(),
          Knowledge.t(),
          CapabilitySnapshot.t(),
          keyword()
        ) :: {:ok, t(), Proposal.t()} | {:error, term()}
  def propose(
        %__MODULE__{pending: %Proposal{} = pending},
        _provider,
        _blueprint,
        _knowledge,
        _capabilities,
        _opts
      ) do
    {:error, {:pending_plan_item, pending.id}}
  end

  def propose(%__MODULE__{} = session, provider, blueprint, knowledge, capabilities, opts) do
    request = next_request(session, blueprint, knowledge, capabilities, opts)

    provider
    |> TextProvider.call(request, request.opts)
    |> proposal_from_response(request)
    |> case do
      {:ok, proposal} -> {:ok, %{session | pending: proposal}, proposal}
      {:error, reason} -> {:error, reason}
    end
  end

  @doc """
  Stores an externally supplied proposal as pending.
  """
  @spec submit(t(), term()) :: {:ok, t(), Proposal.t()} | {:error, term()}
  def submit(%__MODULE__{pending: %Proposal{} = pending}, _proposal) do
    {:error, {:pending_plan_item, pending.id}}
  end

  def submit(%__MODULE__{} = session, proposal) do
    case normalize_proposal(proposal, session) do
      {:ok, proposal} -> {:ok, %{session | pending: proposal}, proposal}
      {:error, reason} -> {:error, reason}
    end
  end

  @doc """
  Accepts the pending proposal or an edited replacement.
  """
  @spec accept(t(), term()) :: {:ok, t(), Proposal.t()} | {:error, term()}
  def accept(%__MODULE__{pending: nil}, :pending), do: {:error, :no_pending_plan_item}
  def accept(%__MODULE__{pending: nil}, _item_or_edit), do: {:error, :no_pending_plan_item}

  def accept(%__MODULE__{} = session, item_or_edit) do
    item = if item_or_edit == :pending, do: session.pending, else: item_or_edit

    with {:ok, proposal} <- normalize_proposal(item, session) do
      accept_proposal(%{session | pending: nil}, proposal)
    end
  end

  @doc """
  Rejects the pending proposal and records feedback for future prompts.
  """
  @spec reject(t(), term()) :: {:ok, t()} | {:error, term()}
  def reject(%__MODULE__{pending: nil}, _reason), do: {:error, :no_pending_plan_item}

  def reject(%__MODULE__{} = session, reason) do
    feedback = String.trim(to_string(reason))
    feedback = if feedback == "", do: "Proposal rejected.", else: feedback
    {:ok, %{session | pending: nil, feedback: session.feedback ++ [feedback]}}
  end

  @doc """
  Builds the executable plan from accepted manual planning items.
  """
  @spec finish_plan(t(), term()) :: {Plan.t(), t(), binary()}
  def finish_plan(%__MODULE__{steps: []} = session, reason) do
    reason = finish_reason(session, reason, "Guided planning finished with no accepted steps.")
    {session.fallback_plan, %{session | finish_reason: reason, pending: nil}, reason}
  end

  def finish_plan(%__MODULE__{} = session, reason) do
    reason = finish_reason(session, reason, "Generated by manual guided planning.")

    plan =
      session.steps
      |> Plan.new(source: :agent_generated, reason: reason)

    {plan, %{session | finish_reason: reason, pending: nil}, reason}
  end

  @spec next_request(t(), MissionBlueprint.t(), Knowledge.t(), CapabilitySnapshot.t(), keyword()) ::
          Request.t()
  defp next_request(
         %__MODULE__{strategy: nil} = session,
         blueprint,
         knowledge,
         capabilities,
         opts
       ) do
    opts = Keyword.put(opts, :planning_feedback, session.feedback)
    Request.guided_strategy(blueprint, knowledge, capabilities, opts)
  end

  defp next_request(%__MODULE__{} = session, blueprint, knowledge, capabilities, opts) do
    opts = Keyword.put(opts, :planning_feedback, session.feedback)

    Request.guided_step(
      blueprint,
      knowledge,
      capabilities,
      session.strategy,
      session.steps,
      length(session.steps) + 1,
      opts
    )
  end

  @spec proposal_from_response(term(), Request.t()) :: {:ok, Proposal.t()} | {:error, term()}
  defp proposal_from_response({:ok, text}, request), do: proposal_from_response(text, request)
  defp proposal_from_response({:error, reason}, _request), do: {:error, reason}

  defp proposal_from_response(text, %Request{mode: :guided_strategy} = request)
       when is_binary(text) do
    strategy = clean_strategy(text)

    {:ok,
     Proposal.new(
       type: :strategy,
       turn: 0,
       prompt: request.prompt,
       response: text,
       strategy: strategy
     )}
  end

  defp proposal_from_response(text, %Request{mode: :guided_step} = request)
       when is_binary(text) do
    case DraftParser.parse_next_step(text) do
      {:ok, step} ->
        {:ok,
         Proposal.new(
           type: :step,
           turn: request.turn,
           prompt: request.prompt,
           response: text,
           step: step
         )}

      {:finish, reason} ->
        {:ok,
         Proposal.new(
           type: :finish,
           turn: request.turn,
           prompt: request.prompt,
           response: text,
           reason: reason
         )}

      {:error, reason} ->
        {:error, {:guided_step_parse_failed, reason}}
    end
  end

  defp proposal_from_response(other, _request), do: {:error, {:invalid_planning_text, other}}

  @spec normalize_proposal(term(), t()) :: {:ok, Proposal.t()} | {:error, term()}
  defp normalize_proposal(%Proposal{} = proposal, _session), do: {:ok, proposal}

  defp normalize_proposal(%Step{} = step, session) do
    {:ok, Proposal.new(type: :step, turn: length(session.steps) + 1, step: step)}
  end

  defp normalize_proposal(text, _session) when is_binary(text) do
    {:ok, Proposal.new(type: :strategy, strategy: text)}
  end

  defp normalize_proposal(attrs, session) when is_map(attrs) or is_list(attrs) do
    attrs = Map.new(attrs)

    cond do
      Map.has_key?(attrs, :type) ->
        normalize_typed_proposal(attrs, session)

      Map.has_key?(attrs, :title) ->
        {:ok, Proposal.new(type: :step, turn: length(session.steps) + 1, step: attrs)}

      Map.has_key?(attrs, :strategy) ->
        {:ok, Proposal.new(type: :strategy, strategy: Map.fetch!(attrs, :strategy))}

      true ->
        {:error, {:invalid_plan_item, attrs}}
    end
  end

  defp normalize_proposal(other, _session), do: {:error, {:invalid_plan_item, other}}

  @spec normalize_typed_proposal(map(), t()) :: {:ok, Proposal.t()} | {:error, term()}
  defp normalize_typed_proposal(%{type: type} = attrs, session) when type in @proposal_types do
    {:ok, Proposal.new(Map.put_new(attrs, :turn, default_turn(attrs, session)))}
  end

  defp normalize_typed_proposal(attrs, _session), do: {:error, {:invalid_plan_item, attrs}}

  @spec accept_proposal(t(), Proposal.t()) :: {:ok, t(), Proposal.t()} | {:error, term()}
  defp accept_proposal(session, %Proposal{type: :strategy, strategy: strategy} = proposal)
       when is_binary(strategy) do
    {:ok, %{session | strategy: strategy, turn: 0}, proposal}
  end

  defp accept_proposal(session, %Proposal{type: :step, step: %Step{} = step} = proposal) do
    step = %{step | source: :generated, status: :pending}
    steps = session.steps ++ [step]
    {:ok, %{session | steps: steps, turn: length(steps)}, %{proposal | step: step}}
  end

  defp accept_proposal(session, %Proposal{type: :finish, reason: reason} = proposal) do
    {:ok, %{session | finish_reason: reason}, proposal}
  end

  defp accept_proposal(session, %Proposal{type: :correction, reason: reason} = proposal) do
    feedback = if reason, do: session.feedback ++ [reason], else: session.feedback
    {:ok, %{session | feedback: feedback}, proposal}
  end

  defp accept_proposal(_session, proposal), do: {:error, {:invalid_plan_item, proposal}}

  @spec default_turn(map(), t()) :: non_neg_integer()
  defp default_turn(%{type: :strategy}, _session), do: 0
  defp default_turn(_attrs, session), do: length(session.steps) + 1

  @spec clean_strategy(binary()) :: binary()
  defp clean_strategy(text) do
    text
    |> String.trim()
    |> String.replace(~r/^\s*strategy\s*:\s*/i, "")
    |> String.trim()
  end

  @spec finish_reason(t(), term(), binary()) :: binary()
  defp finish_reason(%__MODULE__{finish_reason: reason}, nil, default) do
    reason || default
  end

  defp finish_reason(_session, reason, _default) when is_binary(reason), do: reason
  defp finish_reason(_session, reason, _default), do: to_string(reason)
end
